  # Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - src-{{ checksum "package.json" }}
          - src-
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: src-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running tests
          command: yarn lint && yarn test
workflows:
  version: 2
  build:
    jobs:
      - prepare
      - test:
          requires:
          - prepare